"""
Hook argparse-manpage into setup.py generated by poetry
"""

from build_manpages import (
    build_manpages,
    get_build_py_cmd,
    get_install_cmd,
)


def build(setup_kwargs):
    """
    This function is mandatory in order to build the extensions.
    """
    setup_kwargs.update({
        "cmdclass": {
            'build_manpages': build_manpages,
            'build_py': get_build_py_cmd(),
            'install': get_install_cmd(),
        },
    })
