name: juju-jockey
base: core22
adopt-info: juju-jockey
summary: Jockey is a utility for filtering and navigating Juju objects
description: |
  Jockey is a CLI tool designed to facilitate quick and easy retrieval of Juju objects using filters.
  It uses automatic caching of Juju's status in json format to enable faster parsing.
license: MIT
grade: stable
confinement: strict

architectures: [amd64, i386, arm64, armhf, ppc64el]

apps:
  juju-jockey:
    command: bin/juju-jockey
    plugs:
      - home

parts:
  juju-jockey:
    plugin: python
    source: .
    source-type: local
    python-packages:
      - dephell[full]
    build-snaps:
      - jq
      - remarshal
    build-environment:
      - SNAPCRAFT_PYTHON_INTERPRETER: python3.9
    override-build: |
      export PATH="${PATH}:${HOME}/.local/bin"
      python3 -m dephell deps convert --from-path pyproject.toml --from-format poetry --to-path setup.py --to-format setuppy
      snapcraftctl build
      snapcraftctl set-version "$(env -u SNAPCRAFT_PART_INSTALL -u SNAPCRAFT_STAGE -- /snap/bin/toml2json $SNAPCRAFT_PART_BUILD/pyproject.toml | /snap/bin/jq -r '.tool.poetry.version')"
